### ISSUE TITLE
cleaning plan

### ISSUE THREAD

**Issue by CuteEric** [peterWon/CleaningRobot#1]
您好!您这里提到的cleaning plan是指规划清扫路线么？应该启动哪个launch和node？多谢。

**Comment by peterWon** [comment]
@CuteEric path_planning.launch是做路径规划用的, cleaning_*.launch是控制机器人跟着路线走的.

**Comment by CuteEric** [comment]
哦，我准备做一个扫地机器人，需要做全覆盖路径规划。

**Comment by CuteEric** [comment]
您好,看到您更新的Path Planning Result图片87662752.jpg，为什么我得不到这样的结果。
我运行的指令是
roslaunch cleaning_robot path_planning.launch 
机器人没动啊

**Comment by peterWon** [comment]
@CuteEric 
1. 你检查一下launch文件里面的配置文件是否是自己系统上的路径（个别文件我没有写成自动寻包路径）.
2. PathPlanningNode.cpp里面我为了调试把全图路径规划那一行注释了，留下的是边缘循迹规划，你把它改回来再编译一次再试试.
3. 代码基于rbx1相关的几个模拟包，你需要先完全安装好它们.
4. launch文件里面加了一个调试用的选项（launch-prefix="xterm -e gdb --args"），如果不想用调试模式，可以关掉它。
