### ISSUE TITLE
move

### ISSUE THREAD

**Issue by 00bell** [peterWon/CleaningRobot#2]
Hello, I was studying the pathplaning of cleaningrobot  these days. Can you tell me how the robot can follow the path you show in the picture ?  Thanks a lot.

**Comment by peterWon** [comment]
@00bell Just take a look at the file 'cleaning_move.launch', it gives what you want. You need know something about the **ROS's navigation stack** before you make this file work.

**Comment by 00bell** [comment]
是除了边缘检测的那一块（覆盖的路径）显示不出，仿真走不出你图中显示的路径。

**Comment by peterWon** [comment]
你看一下对应的node源文件你就明白了，我把内部路径的那一行注释了，直接运行的话只会显示边缘路径。

**Comment by 00bell** [comment]
>您说的是中的PathPlanningNode中clr.GetPathInROS();  这句对吗 我运行path_planing.launch，出现的路径结果一直是一个resultMat的窗口，黑底绿线的图，无法显示在rviz的地图中。 运行movebase.launch时候一直又卡在The point of step 1364 ，我稍加修改可以移动 遍历路径也看着不对
